application: example
version: dev
runtime: python
api_version: 1
default_expiration: "6d"

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /_ah/login_required
  script: lib/gaetk/gaetk/login.py

- url: /logout
  script: lib/gaetk/gaetk/login.py

- url: .*
  script: main.py
  secure: optional

#error_handlers:
#  - file: templates/error_default.html
#  - error_code: over_quota
#    file: templates/error_over_quota.html
#  - error_code: dos_api_denial
#    file: templates/error_dos_api_denial.html
#  - error_code: timeout
#    file: templates/error_timeout.html

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?CHANGES
- ^(.*/)?LICENSE
- ^(.*/)?Makefile
- ^(.*/)?requirements\.txt
- ^(.*/)?setup.py
- ^(.*/)?docs?/.*
- ^(.*/)?README.*
- ^(.*/)?pythonenv/bin/.*
- ^(.*/)?pythonenv/include/.*
- ^(.*/)?lib/google_appengine/.*
- ^(.*/)?pythonenv/lib/python2.5/site-packages/setuptools.*
- ^(.*/)?pythonenv/lib/python2.5/site-packages/pip.*
- ^(.*/)?pythonenv/lib/python2.5/(encodings|lib-dynload)/.*
